option(MCC_EXAMPLES "Enable building examples" OFF)
option(MCC_TESTING "Enable unit testing" OFF)
option(MCC_DOCS "Generate API documentation using Doxygen" OFF)
option(MCC_FULL_BUILD "Enable every MCC module" OFF)
option(MCC_COVERAGE "Enable coverage instrumentation" OFF)

option(MCC_CORE "Enable MCC::Core" ON)
option(MCC_PITCH "Enable MCC pitch primitives" ON)
option(MCC_INTERVAL "Enable MCC intervals and transposition" ON)
option(MCC_TUNING "Enable MCC tuning and frequencies (uses float)" ON)
option(MCC_SCALE "Enable MCC scales and the scale catalog" ON)
option(MCC_CHORD "Enable MCC chords and the chord catalog" ON)
option(MCC_KEY "Enable MCC keys and key signatures" ON)
option(MCC_NOTATION "Enable MCC text formatting and parsing" ON)
option(MCC_RHYTHM "Enable MCC written rhythm primitives" ON)

if(MCC_FULL_BUILD)
    set(MCC_CORE ON CACHE BOOL "Enable MCC::Core" FORCE)
    set(MCC_PITCH ON CACHE BOOL "Enable MCC pitch primitives" FORCE)
    set(MCC_INTERVAL ON CACHE BOOL "Enable MCC intervals and transposition" FORCE)
    set(MCC_TUNING ON CACHE BOOL "Enable MCC tuning and frequencies (uses float)" FORCE)
    set(MCC_SCALE ON CACHE BOOL "Enable MCC scales and the scale catalog" FORCE)
    set(MCC_CHORD ON CACHE BOOL "Enable MCC chords and the chord catalog" FORCE)
    set(MCC_KEY ON CACHE BOOL "Enable MCC keys and key signatures" FORCE)
    set(MCC_NOTATION ON CACHE BOOL "Enable MCC text formatting and parsing" FORCE)
    set(MCC_RHYTHM ON CACHE BOOL "Enable MCC written rhythm primitives" FORCE)
endif()

if(MCC_INTERVAL AND NOT MCC_PITCH)
    message(FATAL_ERROR "MCC_INTERVAL requires MCC_PITCH")
endif()

if(MCC_RHYTHM AND NOT MCC_PITCH)
    message(FATAL_ERROR "MCC_RHYTHM requires MCC_PITCH")
endif()

if(MCC_KEY AND NOT MCC_SCALE)
    message(FATAL_ERROR "MCC_KEY requires MCC_SCALE")
endif()

if(MCC_NOTATION AND NOT MCC_INTERVAL)
    message(FATAL_ERROR "MCC_NOTATION requires MCC_INTERVAL")
endif()

if(MCC_CHORD AND NOT MCC_SCALE)
    message(FATAL_ERROR "MCC_CHORD requires MCC_SCALE")
endif()

if(MCC_SCALE AND NOT MCC_INTERVAL)
    message(FATAL_ERROR "MCC_SCALE requires MCC_INTERVAL")
endif()

if(MCC_TUNING AND NOT MCC_PITCH)
    message(FATAL_ERROR "MCC_TUNING requires MCC_PITCH")
endif()
