set(MCC_NOTATION_HEADERS
    "${CMAKE_CURRENT_LIST_DIR}/Notation.h")
set(MCC_NOTATION_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/Notation.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Writer.h")

target_sources(MCC PRIVATE ${MCC_NOTATION_HEADERS} ${MCC_NOTATION_SOURCES})
mcc_stage_headers(${MCC_NOTATION_HEADERS})
mcc_add_dox(
    ${MCC_NOTATION_HEADERS}
    "${CMAKE_CURRENT_LIST_DIR}/Notation.dox")

install(FILES ${MCC_NOTATION_HEADERS}
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/MCC/Notation"
    CONFIGURATIONS Release)
