#ifndef SCALE_DEFINITIONS_H
#define SCALE_DEFINITIONS_H
    
    #include "Chromatic.Scale"
    #include "Major.Scale"
    #include "Minor.Scale"
    #include "HarmonicMinor.Scale"
    #include "HarmonicMajor.Scale"
    #include "MajorPentatonic.Scale"
    #include "MinorPentatonic.Scale"
    #include "MinorBlues.Scale"
    #include "MajorBlues.Scale"

    #include "Dorian.Scale"
    #include "Phrygian.Scale"
    #include "Lydian.Scale"
    #include "Mixolydian.Scale"
    #include "Locrian.Scale"

    #include "Algerian.Scale"
    #include "Arabic.Scale"
    #include "Augmented.Scale"
    #include "Pelog.Scale"
    #include "Byzantine.Scale"
    #include "Chinese.Scale"
    #include "Diminished.Scale"
    #include "Egyptian.Scale"
    #include "EightToneSpanish.Scale"
    #include "Enigmatic.Scale"
    #include "Ethiopian.Scale"
    #include "Hindu.Scale"
    #include "Hirajoshi.Scale"
    #include "HungarianMinor.Scale"
    #include "Japanese.Scale"
    #include "Oriental.Scale"
    #include "WholeTone.Scale"
    #include "RomanianMinor.Scale"
    #include "SpanishGypsy.Scale"
    #include "SuperLocrian.Scale"

#endif//SCALE_DEFINITIONS_H
