set(MCC_SRC_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")

add_library(MCC STATIC)
add_library(MCC::MCC ALIAS MCC)

target_compile_features(MCC PUBLIC cxx_std_${MCC_REQUIRED_CXX_STANDARD})
target_link_libraries(MCC PUBLIC Foundation::Foundation)

set(MCC_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/artifacts")
set_target_properties(MCC PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${MCC_OUTPUT_DIRECTORY}/lib"
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${MCC_OUTPUT_DIRECTORY}/lib"
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${MCC_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY "${MCC_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY_DEBUG "${MCC_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY_RELEASE "${MCC_OUTPUT_DIRECTORY}/lib"
    RUNTIME_OUTPUT_DIRECTORY "${MCC_OUTPUT_DIRECTORY}/bin"
    RUNTIME_OUTPUT_DIRECTORY_DEBUG "${MCC_OUTPUT_DIRECTORY}/bin"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE "${MCC_OUTPUT_DIRECTORY}/bin"
    OUTPUT_NAME "MCC"
    DEBUG_POSTFIX "_d")

set(MCC_BUILD_INCLUDE_DIR
    "${CMAKE_BINARY_DIR}/include/MCC-${PROJECT_VERSION}")

set(MCC_TOP_LEVEL_HEADERS
    "${CMAKE_CURRENT_LIST_DIR}/MCC.h"
    "${CMAKE_CURRENT_LIST_DIR}/MCC_BuildSettings.h")

if(MCC_CORE)
    list(APPEND MCC_TOP_LEVEL_HEADERS
        "${CMAKE_CURRENT_LIST_DIR}/MCC_Core.h")
endif()

if(MCC_PITCH)
    list(APPEND MCC_TOP_LEVEL_HEADERS
        "${CMAKE_CURRENT_LIST_DIR}/MCC_Pitch.h")
endif()

if(MCC_INTERVAL)
    list(APPEND MCC_TOP_LEVEL_HEADERS
        "${CMAKE_CURRENT_LIST_DIR}/MCC_Interval.h")
endif()

if(MCC_TUNING)
    list(APPEND MCC_TOP_LEVEL_HEADERS
        "${CMAKE_CURRENT_LIST_DIR}/MCC_Tuning.h")
endif()

if(MCC_SCALE)
    list(APPEND MCC_TOP_LEVEL_HEADERS
        "${CMAKE_CURRENT_LIST_DIR}/MCC_Scale.h")
endif()

target_sources(MCC PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/MCC.cpp"
    ${MCC_TOP_LEVEL_HEADERS})

target_include_directories(MCC
    PUBLIC
        $<BUILD_INTERFACE:${MCC_BUILD_INCLUDE_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

mcc_stage_headers(${MCC_TOP_LEVEL_HEADERS})
mcc_add_dox(
    ${MCC_TOP_LEVEL_HEADERS}
    "${CMAKE_CURRENT_LIST_DIR}/MCCTop.dox")

if(MCC_CORE)
    mcc_add_macro(PUBLIC MCC_CORE)
endif()

if(MCC_PITCH)
    mcc_add_macro(PUBLIC MCC_PITCH)
endif()

if(MCC_INTERVAL)
    mcc_add_macro(PUBLIC MCC_INTERVAL)
endif()

if(MCC_TUNING)
    mcc_add_macro(PUBLIC MCC_TUNING)
endif()

if(MCC_SCALE)
    mcc_add_macro(PUBLIC MCC_SCALE)
endif()

if(MCC_CORE OR MCC_PITCH OR MCC_INTERVAL OR MCC_TUNING OR MCC_SCALE)
    add_subdirectory(MCC)
endif()

install(TARGETS MCC
    EXPORT MCCTargets
    CONFIGURATIONS Release
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")

install(FILES ${MCC_TOP_LEVEL_HEADERS}
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
    CONFIGURATIONS Release)

install(EXPORT MCCTargets
    FILE MCCTargets.cmake
    NAMESPACE MCC::
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/MCC"
    CONFIGURATIONS Release)
